# -*- coding: utf-8 -*-
"""Fruits.KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10aAHbCtEB3rx6ef_IelHVoxIBggY4Rdb
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

df=pd.read_excel("/content/FRUITS.xlsx")
df

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Size']=le.fit_transform(df['Size'])
x=df[['Weight(grams)','Color Intensity(0-10)','Size']].values
y=df['Fruit Type'].values
print(x)
print(y)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x=scaler.fit_transform(x)
print(x)

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
print(y_pred)

new=np.array([140,7,0]).reshape(1, -1)# Reshape to a 2D array with one row
y_pred=knn.predict(new)
print(y_pred)

from sklearn.metrics import accuracy_score
# Calculate accuracy using y_test and predictions on the test set
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

