# -*- coding: utf-8 -*-
"""Vehicale.car.datasets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3LgxQEbsg1FOA7tWgGq1S_sS8AjX390
"""

import pandas as pd
import numpy as np
df=pd.read_csv("/content/Craigslist Car Dataset.csv")
df

df.head(6)

x = df[["year", "odometer", "condition"]]
y=df[["price"]]
print(x)
print(y)

df.fillna("odometer")
df.fillna("condition")
df.fillna("price")

from sklearn import preprocessing
le= preprocessing.LabelEncoder()
x["condition"]=le.fit_transform(x["condition"])
print(x)
le= preprocessing.LabelEncoder()
x["price"]=le.fit_transform(x["price"])
print(x)
le= preprocessing.LabelEncoder()
x["odometer"]=le.fit_transform(x["odometer"])
print(x)

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
logreg = LinearRegression()
logreg.fit(x_train, y_train)
y_pred = logreg.predict(x_test)
print(y_pred)